<a href="https://colab.research.google.com/github/Sourav-Manik/AI_Deep_Learning/blob/main/Without_Word2Vec_create_our_own_word_embeddings.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#With keras embedding layer we can create our own word embeddings

In [ ]:
import keras

In [ ]:
from numpy import array
from keras.preprocessing.text import one_hot
from keras.utils import pad_sequences
from keras.models import Sequential
from keras.layers import Dense, Flatten,Embedding

In [ ]:
#Define your own documents
sentences = ['hello how are you',
             'how are you',
             'whats going on',
             'I am doing great',
             'You are awesome',
             'I really love you so much']

In [ ]:
sent_labels = array([1,1,1,0,0,0])

In [ ]:
vocab_size = 50 #dimension

In [ ]:
encoded_sent = [one_hot(i,vocab_size) for i in sentences]
encoded_sent

[[45, 11, 31, 41],
 [11, 31, 41],
 [46, 36, 5],
 [41, 44, 21, 10],
 [41, 31, 43],
 [41, 1, 7, 41, 29, 38]]

In [ ]:
#Now I want my nn to train, for that the size of the vector should be same.
padded_sent = pad_sequences(encoded_sent,maxlen = 6, padding = 'pre')
print(padded_sent)

[[ 0  0 45 11 31 41]
 [ 0  0  0 11 31 41]
 [ 0  0  0 46 36  5]
 [ 0  0 41 44 21 10]
 [ 0  0  0 41 31 43]
 [41  1  7 41 29 38]]


In [ ]:
mymodel = Sequential()
mymodel.add(Embedding(vocab_size,output_dim = 8,input_length = 6)) #6 sentences
mymodel.add(Flatten())
mymodel.add(Dense(1,activation = 'sigmoid')) #because target is categorical in nature

In [ ]:
mymodel.compile(optimizer = 'adam',loss = 'binary_crossentropy',metrics = ['accuracy'])

In [ ]:
mymodel.fit(padded_sent,sent_labels,epochs = 30)

In [ ]:
#Evalute the model
mymodel.evaluate(padded_sent,sent_labels,verbose = 1)

1/1 [==============================] - 0s 115ms/step - loss: 0.6238 - accuracy: 0.8333


[0.6238057017326355, 0.8333333134651184]

In [ ]:
model_loss,model_accuracy = mymodel.evaluate(padded_sent,sent_labels,verbose = 1)
print('Accuracy : %f' %(model_accuracy*100))

1/1 [==============================] - 0s 20ms/step - loss: 0.6238 - accuracy: 0.8333
Accuracy : 83.333331


The prediction Part

In [ ]:
sent_for_pred = ['hello how are you',
                 'I am doing great']

In [ ]:
vocab_size = 50 
encoded = [one_hot(i,vocab_size)for i in sent_for_pred]
encoded

[[45, 11, 31, 41], [41, 44, 21, 10]]

In [ ]:
#Now I want my nn to train, for that the size of the vector should be same.
padded_sent = pad_sequences(encoded,maxlen = 6, padding = 'pre')
print(padded_sent)

[[ 0  0 45 11 31 41]
 [ 0  0 41 44 21 10]]


In [ ]:
predict_x = mymodel.predict(padded_sent)
predict_x

1/1 [==============================] - 0s 58ms/step


array([[0.5361289],
       [0.4518984]], dtype=float32)

In [ ]:
#For sentence 1 the accuracy is more than 0.5 thus it will belong to class 1 and for sentence 2 it's vice versa.


In [ ]:
#Conclusion - As the vocal is so small, the model performance won't be that great.