<a href="https://colab.research.google.com/github/Sourav-Manik/AI_Deep_Learning/blob/main/Word2Vec_Vs_BERT.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install flair

In [ ]:
# from torch.nn.modules import distance
import numpy as np
from flair.embeddings import WordEmbeddings, TransformerWordEmbeddings
from flair.data import Sentence
from scipy.spatial import distance

#Word2Vec - Glove Embedding

In [ ]:
glove_embedding = WordEmbeddings('glove')
#we know that word2vec model creates vector for a word that is independent of the context.
#i.e, Numeric representation of a word will remain same irrespective of the context of a particular word.
#Glove is also a WordEmbedding model

##Sentence 1

In [ ]:
sentence_1 = Sentence("The founder of Apple is Steve Jobs")

In [ ]:
glove_embedding.embed(sentence_1)

[Sentence: "The founder of Apple is Steve Jobs"]

In [ ]:
for token in sentence_1:
  print(token)
  print(token.embedding)
  print("\n")

Token[0]: "The"
tensor([-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344,
        -0.5755,  0.0875,  0.2879, -0.0673,  0.3091, -0.2638, -0.1323, -0.2076,
         0.3340, -0.3385, -0.3174, -0.4834,  0.1464, -0.3730,  0.3458,  0.0520,
         0.4495, -0.4697,  0.0263, -0.5415, -0.1552, -0.1411, -0.0397,  0.2828,
         0.1439,  0.2346, -0.3102,  0.0862,  0.2040,  0.5262,  0.1716, -0.0824,
        -0.7179, -0.4153,  0.2033, -0.1276,  0.4137,  0.5519,  0.5791, -0.3348,
        -0.3656, -0.5486, -0.0629,  0.2658,  0.3020,  0.9977, -0.8048, -3.0243,
         0.0125, -0.3694,  2.2167,  0.7220, -0.2498,  0.9214,  0.0345,  0.4674,
         1.1079, -0.1936, -0.0746,  0.2335, -0.0521, -0.2204,  0.0572, -0.1581,
        -0.3080, -0.4162,  0.3797,  0.1501, -0.5321, -0.2055, -1.2526,  0.0716,
         0.7056,  0.4974, -0.4206,  0.2615, -1.5380, -0.3022, -0.0734, -0.2831,
         0.3710, -0.2522,  0.0162, -0.0171, -0.3898,  0.8742, -0.7257, -0.5106,
        -0.5203, -0.1459

In [ ]:
sentence_1[0]

Token[0]: "The"

In [ ]:
sentence_1[1]

Token[1]: "founder"

In [ ]:
sentence_1[0].embedding

tensor([-0.0382, -0.2449,  0.7281, -0.3996,  0.0832,  0.0440, -0.3914,  0.3344,
        -0.5755,  0.0875,  0.2879, -0.0673,  0.3091, -0.2638, -0.1323, -0.2076,
         0.3340, -0.3385, -0.3174, -0.4834,  0.1464, -0.3730,  0.3458,  0.0520,
         0.4495, -0.4697,  0.0263, -0.5415, -0.1552, -0.1411, -0.0397,  0.2828,
         0.1439,  0.2346, -0.3102,  0.0862,  0.2040,  0.5262,  0.1716, -0.0824,
        -0.7179, -0.4153,  0.2033, -0.1276,  0.4137,  0.5519,  0.5791, -0.3348,
        -0.3656, -0.5486, -0.0629,  0.2658,  0.3020,  0.9977, -0.8048, -3.0243,
         0.0125, -0.3694,  2.2167,  0.7220, -0.2498,  0.9214,  0.0345,  0.4674,
         1.1079, -0.1936, -0.0746,  0.2335, -0.0521, -0.2204,  0.0572, -0.1581,
        -0.3080, -0.4162,  0.3797,  0.1501, -0.5321, -0.2055, -1.2526,  0.0716,
         0.7056,  0.4974, -0.4206,  0.2615, -1.5380, -0.3022, -0.0734, -0.2831,
         0.3710, -0.2522,  0.0162, -0.0171, -0.3898,  0.8742, -0.7257, -0.5106,
        -0.5203, -0.1459,  0.8278,  0.27

In [ ]:
sentence_1[0].embedding.shape

torch.Size([100])

##Sentence 2

In [ ]:
sentence_2 = Sentence("An Apple a day keeps a doctor away")

In [ ]:
glove_embedding.embed(sentence_2)

[Sentence: "An Apple a day keeps a doctor away"]

In [ ]:
for token in sentence_2:
  print(token)
  print(token.embedding)
  print("\n")

Token[0]: "An"
tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,

In [ ]:
sentence_2[0]

Token[0]: "An"

In [ ]:
sentence_2[1]

Token[1]: "Apple"

In [ ]:
sentence_2[0].embedding

tensor([-0.4214, -0.1880,  0.4624, -0.1761,  0.3621,  0.3670,  0.2792,  0.1463,
        -0.0542,  0.4583,  0.0654, -0.3372,  0.0675, -0.3632,  0.5030, -0.0104,
         0.7283, -0.1756, -0.3400,  0.0729,  0.6448, -0.2391,  0.3838,  0.1386,
         1.0994, -0.2488, -0.1508, -0.4874, -0.2304,  0.0648, -0.7018,  0.8265,
         0.0613,  0.1853, -0.3016, -0.0222,  0.3430,  0.8033,  0.1714,  0.1546,
        -0.5076,  0.3957,  0.0543, -0.5308,  0.4825,  0.0862,  0.5958, -0.2238,
        -0.3955, -0.7304, -0.1028, -0.3917,  1.2290,  1.2129, -1.0365, -3.4971,
         0.1092, -1.0084,  1.9998,  0.7964,  0.3881,  0.4375,  0.0852,  0.3855,
         0.6199, -1.0320,  0.7012, -0.2246,  0.0794,  0.0913, -0.2120, -0.5543,
        -0.0534, -0.8020,  0.4680, -0.0501, -0.5742, -0.0848, -1.7227, -0.9429,
         0.9867,  0.3121, -0.3774,  0.0687, -0.7784, -0.2849,  0.8105,  0.4660,
        -0.1186, -0.9341,  0.3372,  0.0379, -0.1827, -0.0199,  0.2049, -0.4772,
        -0.4925, -0.5652,  0.7256, -0.15

In [ ]:
sentence_2[0].embedding.shape

torch.Size([100])

##Glove distance between the same word

In [ ]:
#We know that in sent_1 --> Apple is pointing towards an organization.
#And in sent_2 --> It is pointing towards an apple.

In [ ]:
print(sentence_1)
print(sentence_2)

Sentence: "The founder of Apple is Steve Jobs"
Sentence: "An Apple a day keeps a doctor away"


In [ ]:
glove_dist = distance.euclidean(np.array(sentence_1[3].embedding),
                                np.array(sentence_2[1].embedding))
print("Distance between Apple embeddings for Glove = {}".format(glove_dist))

Distance between Apple embeddings for Glove = 0.0


In [ ]:
#Takeaway:

#So word2vec model don't understand the context of the word. To prove the hypothesis, we have taken the vectors represnetation of Apple in both the sentences.
#Lets calculate the eculidean distance of the word Apple in two sentences.
#Zero difference. So word2vec is context independent,i.e. never understand the context.

#BERT Embedding

In [ ]:
bert_embedding = TransformerWordEmbeddings('bert-base-multilingual-cased')
bert_embedding

TransformerWordEmbeddings(
  (model): BertModel(
    (embeddings): BertEmbeddings(
      (word_embeddings): Embedding(119547, 768, padding_idx=0)
      (position_embeddings): Embedding(512, 768)
      (token_type_embeddings): Embedding(2, 768)
      (LayerNorm): LayerNorm((768,), eps=1e-12, elementwise_affine=True)
      (dropout): Dropout(p=0.1, inplace=False)
    )
    (encoder): BertEncoder(
      (layer): ModuleList(
        (0): BertLayer(
          (attention): BertAttention(
            (self): BertSelfAttention(
              (query): Linear(in_features=768, out_features=768, bias=True)
              (key): Linear(in_features=768, out_features=768, bias=True)
              (value): Linear(in_features=768, out_features=768, bias=True)
              (dropout): Dropout(p=0.1, inplace=False)
            )
            (output): BertSelfOutput(
              (dense): Linear(in_features=768, out_features=768, bias=True)
              (LayerNorm): LayerNorm((768,), eps=1e-12, elementwi

In [ ]:
bert_embedding.embed(sentence_1)
for token in sentence_1:
  print(token)
  print(token.embedding)

Token[0]: "The"
tensor([-3.8194e-02, -2.4487e-01,  7.2812e-01, -3.9961e-01,  8.3172e-02,
         4.3953e-02, -3.9141e-01,  3.3440e-01, -5.7545e-01,  8.7459e-02,
         2.8787e-01, -6.7310e-02,  3.0906e-01, -2.6384e-01, -1.3231e-01,
        -2.0757e-01,  3.3395e-01, -3.3848e-01, -3.1743e-01, -4.8336e-01,
         1.4640e-01, -3.7304e-01,  3.4577e-01,  5.2041e-02,  4.4946e-01,
        -4.6971e-01,  2.6280e-02, -5.4155e-01, -1.5518e-01, -1.4107e-01,
        -3.9722e-02,  2.8277e-01,  1.4393e-01,  2.3464e-01, -3.1021e-01,
         8.6173e-02,  2.0397e-01,  5.2624e-01,  1.7164e-01, -8.2378e-02,
        -7.1787e-01, -4.1531e-01,  2.0335e-01, -1.2763e-01,  4.1367e-01,
         5.5187e-01,  5.7908e-01, -3.3477e-01, -3.6559e-01, -5.4857e-01,
        -6.2892e-02,  2.6584e-01,  3.0205e-01,  9.9775e-01, -8.0481e-01,
        -3.0243e+00,  1.2540e-02, -3.6942e-01,  2.2167e+00,  7.2201e-01,
        -2.4978e-01,  9.2136e-01,  3.4514e-02,  4.6745e-01,  1.1079e+00,
        -1.9358e-01, -7.4575e-02,  

In [ ]:
sentence_1[3]

Token[3]: "Apple"

In [ ]:
sentence_1[3].embedding

tensor([-5.9850e-01, -4.6321e-01,  1.3001e-01, -1.9576e-02,  4.6030e-01,
        -3.0180e-01,  8.9770e-01, -6.5634e-01,  6.6858e-01, -4.9164e-01,
         3.7557e-02, -5.0889e-02,  6.4510e-01, -5.3882e-01, -3.7650e-01,
        -4.3120e-02,  5.1384e-01,  1.7783e-01,  2.8596e-01,  9.2063e-01,
        -4.9349e-01, -4.8583e-01,  6.1321e-01,  7.8211e-01,  1.9254e-01,
         9.1228e-01, -5.5596e-02, -1.2512e-01, -6.5688e-01,  6.8557e-02,
         5.5629e-01,  1.6110e+00, -7.3642e-03, -4.8879e-01,  4.5493e-01,
         9.6105e-01, -6.3369e-02,  1.7432e-01,  9.8140e-01, -1.3125e+00,
        -1.5801e-01, -5.4301e-01, -1.3888e-01, -2.6146e-01, -3.6910e-01,
         2.6844e-01, -2.4375e-01, -1.9484e-01,  6.2583e-01, -7.3770e-01,
         3.8351e-01, -7.5004e-01, -3.9053e-01,  9.1498e-02, -3.6591e-01,
        -1.4715e+00, -4.5228e-01,  2.2560e-01,  1.1412e+00, -3.8526e-01,
        -6.7160e-02,  5.7288e-01, -3.9191e-01,  3.1302e-01, -2.9235e-01,
        -9.6157e-01,  1.5154e-01, -2.1659e-01,  2.5

In [ ]:
sentence_1[3].embedding.shape

torch.Size([868])

In [ ]:
bert_embedding.embed(sentence_2)
for token in sentence_2:
  print(token)
  print(token.embedding)

Token[0]: "An"
tensor([-4.2140e-01, -1.8797e-01,  4.6241e-01, -1.7605e-01,  3.6212e-01,
         3.6701e-01,  2.7924e-01,  1.4634e-01, -5.4227e-02,  4.5834e-01,
         6.5416e-02, -3.3725e-01,  6.7505e-02, -3.6316e-01,  5.0302e-01,
        -1.0361e-02,  7.2826e-01, -1.7564e-01, -3.3996e-01,  7.2864e-02,
         6.4481e-01, -2.3908e-01,  3.8383e-01,  1.3858e-01,  1.0994e+00,
        -2.4883e-01, -1.5078e-01, -4.8738e-01, -2.3042e-01,  6.4788e-02,
        -7.0183e-01,  8.2654e-01,  6.1280e-02,  1.8531e-01, -3.0162e-01,
        -2.2151e-02,  3.4302e-01,  8.0331e-01,  1.7135e-01,  1.5462e-01,
        -5.0759e-01,  3.9572e-01,  5.4291e-02, -5.3081e-01,  4.8252e-01,
         8.6205e-02,  5.9585e-01, -2.2377e-01, -3.9550e-01, -7.3036e-01,
        -1.0279e-01, -3.9166e-01,  1.2290e+00,  1.2129e+00, -1.0365e+00,
        -3.4971e+00,  1.0923e-01, -1.0084e+00,  1.9998e+00,  7.9640e-01,
         3.8810e-01,  4.3746e-01,  8.5194e-02,  3.8549e-01,  6.1993e-01,
        -1.0320e+00,  7.0119e-01, -2

In [ ]:
sentence_2[1]

Token[1]: "Apple"

In [ ]:
sentence_2[1].embedding

tensor([-5.9850e-01, -4.6321e-01,  1.3001e-01, -1.9576e-02,  4.6030e-01,
        -3.0180e-01,  8.9770e-01, -6.5634e-01,  6.6858e-01, -4.9164e-01,
         3.7557e-02, -5.0889e-02,  6.4510e-01, -5.3882e-01, -3.7650e-01,
        -4.3120e-02,  5.1384e-01,  1.7783e-01,  2.8596e-01,  9.2063e-01,
        -4.9349e-01, -4.8583e-01,  6.1321e-01,  7.8211e-01,  1.9254e-01,
         9.1228e-01, -5.5596e-02, -1.2512e-01, -6.5688e-01,  6.8557e-02,
         5.5629e-01,  1.6110e+00, -7.3642e-03, -4.8879e-01,  4.5493e-01,
         9.6105e-01, -6.3369e-02,  1.7432e-01,  9.8140e-01, -1.3125e+00,
        -1.5801e-01, -5.4301e-01, -1.3888e-01, -2.6146e-01, -3.6910e-01,
         2.6844e-01, -2.4375e-01, -1.9484e-01,  6.2583e-01, -7.3770e-01,
         3.8351e-01, -7.5004e-01, -3.9053e-01,  9.1498e-02, -3.6591e-01,
        -1.4715e+00, -4.5228e-01,  2.2560e-01,  1.1412e+00, -3.8526e-01,
        -6.7160e-02,  5.7288e-01, -3.9191e-01,  3.1302e-01, -2.9235e-01,
        -9.6157e-01,  1.5154e-01, -2.1659e-01,  2.5

In [ ]:
sentence_2[1].embedding.shape

torch.Size([868])

In [ ]:
BERT_dist = distance.euclidean(np.array(sentence_1[3].embedding),
                                np.array(sentence_2[1].embedding))
print("Distance between Apple embeddings for BERT = {}".format(BERT_dist))

Distance between Apple embeddings for BERT = 14.77230167388916


In [ ]:
#End